name: C/C++ CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development", "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake ..
    - name: make
      run: make
    - name: run
      run: ./JunLang.exe
    - uses: actions/upload-artifact@v4
      with:
        name: JunLang
        path: ./JunLang.exe
